baseURL: "https://granddaifuku.com/"

languageCode: "en-us"
title: "Yudai Fukushima's webpage"
theme: "toha"

# enableGitInfo = true
# DefaultContentLanguageInSubdir = true

languages:
  en:
    languageName: English
    weight: 1
  jp:
    languageName: 日本語
    weight: 3

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable Google Analytics
# googleAnalytics: UA-122321624-2

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # Background image of the landing page
  background: /images/site/background.png

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  logo:
    main: /images/site/daifuku.png
    # inverted: /images/site/inverted-logo.png
    # favicon: /images/site/favicon.png

  # GitHub repo of your site
  gitRepo: https://github.com/granddaifuku/granddaifuku.com
  # Default branch of your Git repo
  gitBranch: main

  # Configure various features of this theme
  features:
    # Enable and configure portfolio
    portfolio:
      enable: true
    # Enable and configure blog posts
    blog:
      enable: true
      # Share post on different social media
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        reddit: true
        whatsapp: true
        email: true
        # tumblr: true
        # pocket: true
        # diaspora: true
        # mastodon: true

    # Enable & configure "Notes" features
    notes:
      enable: false

    # Enable comment feature. There, should be only one of them.
    comment:
      enable: false
      disqus:
        shortName: toha-example-site
      # valine:
      #   appId: HTV6askWxVo3vOxlqjjaq2hd-MsYXbMMI
      #   appKey: pVrT3C85KGIuk27t07eh6bUC
      #   avatar: retro
      #   placeholder: Share your thought.
      #   lang: en
      #   recordIP: true
      #   enableQQ: true
      # utteranc:
      #   repo: github.com/hugo-toha/hugo-toha.github.io
      #   issueTerm: title
      #   theme: github-light

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Show tags under the post title
  enableTags: true

  # If you want to use different country flag for a language, specify them here.
  flagOverwrites:
  - languageCode: en
    countryCode: us
  - languageCode: jp
    countryCode: jp

  # Provide footer configuration.
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: true

    # Show/hide newsletter section in the footer. Default is "true".
    # Currently, it supports "mailchimp".
    newsletter:
      enable: false

    # Show/hide disclaimer notice in the footer. Default is "false".
    disclaimer:
      enable: true
